In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ 1 , 2 , 3 , 4 , 5 ]
array_list = np.array(object = list_)
array_list

array([1, 2, 3, 4, 5])

<h3>Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

<h4>Yes, there is a difference in the data types of the variables list_ and array_list. list_ is a Python list, while array_list is a NumPy array. 

In [2]:
array_list = np.array(list_)
type(list_) 


list

In [3]:
type(array_list)

numpy.ndarray

<h3>Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


In [4]:
variables_list = ['mohit',5,56,100,10.5]
arra_list = np.array([1,2,3,56,7,89])

In [5]:
def iter(x):
    for i in x:        
        print(type(i))

In [6]:
iter(variables_list)

<class 'str'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'float'>


In [7]:
iter(arra_list)

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


<h3>Q3. Considering the following changes in the variable, array_list:

<br>array_list = np.array(object = list_, dtype = int)
<br>Will there be any difference in the data type of the elements present in both the variables, list_ and
<br>arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
<br>
<br>Consider the below code to answer further questions:
<br>
<br>
<br>import numpy as np
<br>num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
<br>num_array = np.array(object = num_list)


In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [10]:
iter(num_array)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
iter(num_list)

<class 'list'>
<class 'list'>


<h3>Q4. Write a code to find the following characteristics of variable, num_array:
<br>(i) shape
<br>(ii) size


In [12]:
#Shape function describes dimensions of array 
num_array.shape

(2, 3)

In [13]:
#Size function describes the total number of element present in array
num_array.size

6

<h3>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
<br>[Hint: The size of the array will be 9 and the shape will be (3,3).]


In [14]:
mat = np.zeros((3,3))

In [15]:
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<h3>Q6. Create an identity matrix of shape (5,5) using numpy functions?
<br>[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
i_mat = np.eye(5)
i_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])